# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
    ]
